### PR TITLE
sign up and guest login basics

### PR DESCRIPTION
**Pull request by digitalSalt**
sign up and guest user login. Changes likely needed as we progress on the app

### CODE REVIEW

**Comment by digitalSalt** [comment]
seems like @kevinzhangftw tested this from the UI. 
@veriest @tudatn @BrendinGreen hopefully this can be closed before our meeting on Tues, after you guys pass it.

**Comment by BrendinGreen** [comment]
Working on styles now. At the moment I am using bootstrap, but we can always use something like propeller or another front end framework.

**Comment by digitalSalt** [comment]
@BrendinGreen bootstrap sounds good to me

**Comment by digitalSalt** [comment]
gonna close this to not block other changes coming to dev branch. I think in the future, pull req should be from out individual branches to dev - and once in a while dev is merged to master.

**Pull request merged**
